/**
 * Parity with the Python implementation. Fixtures are generated by
 * scripts/fixtures/gen_theraq_fixtures.py from the real Python code.
 */
import { describe, it, expect } from 'vitest';
import engineFixture from '../__fixtures__/engine_cases.json';
import pipelineFixture from '../__fixtures__/pipeline_cases.json';
import { computeTheraqMetrics, TheraqEngine, THERAQ_DEFINITIONS, type ConditionSpectra } from '../engine';
import { analyzeTheraq, TheraqAnalysisError } from '../analyze';
import type { PhaseEpochs } from '../spectrum';
import type { TheraqPhase } from '@/lib/theraq';

const REL_TOL = 1e-6;

type Json = null | boolean | number | string | Json[] | { [k: string]: Json };

/** Max relative error between two JSON trees with identical structure (throws on mismatch). */
function maxRelError(actual: Json, expected: Json, path = '$'): number {
  if (typeof expected === 'number' && typeof actual === 'number') {
    if (actual === expected) return 0;
    return Math.abs(actual - expected) / Math.max(Math.abs(expected), 1e-12);
  }
  if (Array.isArray(expected)) {
    if (!Array.isArray(actual) || actual.length !== expected.length) {
      throw new Error(`${path}: array shape differs`);
    }
    return expected.reduce<number>((m, e, i) => Math.max(m, maxRelError(actual[i], e, `${path}[${i}]`)), 0);
  }
  if (expected && typeof expected === 'object') {
    if (!actual || typeof actual !== 'object' || Array.isArray(actual)) throw new Error(`${path}: not an object`);
    const keys = new Set([...Object.keys(expected), ...Object.keys(actual)]);
    let m = 0;
    for (const k of keys) m = Math.max(m, maxRelError(actual[k] ?? null, expected[k] ?? null, `${path}.${k}`));
    return m;
  }
  if (actual !== expected) throw new Error(`${path}: ${JSON.stringify(actual)} !== ${JSON.stringify(expected)}`);
  return 0;
}

const asJson = (v: unknown): Json => JSON.parse(JSON.stringify(v));

describe('engine parity (spectra -> metrics/indices)', () => {
  const { channels, domain, cases } = engineFixture as unknown as {
    channels: string[];
    domain: number[];
    cases: Array<{
      name: string;
      spectra: ConditionSpectra;
      expected: Json;
      expected_selected: Record<string, Json>;
    }>;
  };

  it.each(cases.map((c) => [c.name, c] as const))('%s matches Python exactly', (_name, c) => {
    const actual = asJson(computeTheraqMetrics(channels, c.spectra, domain));
    expect(actual).toEqual(c.expected);

    const engine = new TheraqEngine(channels, c.spectra, domain);
    for (const def of THERAQ_DEFINITIONS.dysregulatedIndexMetrics) {
      expect(asJson(engine.selectAbnormal(def))).toEqual(c.expected_selected[def.name!]);
    }
  });
});

type PhaseInput = { sfreq: number; channels: string[]; badChannels: string[]; epochs: number[][][] };
type Mutation =
  | { kind: 'none' }
  | { kind: 'drop_phase'; phase: TheraqPhase }
  | { kind: 'drop_channel'; phase: TheraqPhase; channel: string }
  | { kind: 'keep_epochs'; phase: TheraqPhase; n: number };

/** Mirror of _apply() in the generator. */
function applyMutation(inputs: Record<string, PhaseInput>, m: Mutation): Record<string, PhaseInput> {
  const out: Record<string, PhaseInput> = structuredClone(inputs);
  if (m.kind === 'drop_phase') delete out[m.phase];
  if (m.kind === 'drop_channel') {
    const p = out[m.phase];
    const ci = p.channels.indexOf(m.channel);
    p.channels.splice(ci, 1);
    for (const ep of p.epochs) ep.splice(ci, 1);
  }
  if (m.kind === 'keep_epochs') out[m.phase].epochs = out[m.phase].epochs.slice(0, m.n);
  return out;
}

function toPhaseEpochs(inputs: Record<string, PhaseInput>): Partial<Record<TheraqPhase, PhaseEpochs>> {
  const out: Partial<Record<TheraqPhase, PhaseEpochs>> = {};
  for (const [phase, p] of Object.entries(inputs)) {
    out[phase as TheraqPhase] = {
      sfreq: p.sfreq,
      channels: p.channels,
      badChannels: p.badChannels,
      epochs: p.epochs.map((ep) => ep.map((ch) => Float64Array.from(ch))),
    };
  }
  return out;
}

describe('pipeline parity (epochs -> results)', () => {
  const { inputs, variants } = pipelineFixture as unknown as {
    inputs: Record<string, PhaseInput>;
    variants: Array<{
      name: string;
      mutation: Mutation;
      config: { theraq_min_epochs?: number; theraq_reject_mad_k?: number };
      expected: { error?: string; result?: Record<string, Json> };
    }>;
  };

  it.each(variants.map((v) => [v.name, v] as const))('%s', (_name, v) => {
    const phases = toPhaseEpochs(applyMutation(inputs, v.mutation));
    const opts = { minCleanEpochs: v.config.theraq_min_epochs, rejectMadK: v.config.theraq_reject_mad_k };

    if (v.expected.error) {
      expect(() => analyzeTheraq(phases, opts)).toThrow(TheraqAnalysisError);
      expect(() => analyzeTheraq(phases, opts)).toThrow(v.expected.error);
      return;
    }

    const actual = asJson(analyzeTheraq(phases, opts)) as Record<string, Json>;
    const expected = v.expected.result!;

    // Exact: QC counts, channel set, ratings, index scores, metric values (2 dp).
    expect(actual.phases).toEqual(expected.phases);
    expect(actual.channel_names).toEqual(expected.channel_names);
    expect(actual.spectra_domain).toEqual(expected.spectra_domain);
    expect(actual.metrics).toEqual(expected.metrics);
    expect(actual.indices).toEqual(expected.indices);
    expect(actual.disclaimer).toBe(expected.disclaimer);

    // Spectra: FFT implementations differ in the last bits.
    const spectraErr = maxRelError(actual.spectra, expected.spectra);
    expect(spectraErr).toBeLessThan(REL_TOL);

    const { engine, processing_time_seconds, ...meta } = actual.processing_metadata as Record<string, Json>;
    expect(engine).toBe('node');
    expect(typeof processing_time_seconds).toBe('number');
    expect(meta).toEqual(expected.processing_metadata);

    console.info(`[theraq parity] ${v.name}: spectra max rel err ${spectraErr.toExponential(2)}`);
  });
});
